### ISSUE TITLE
Deprecated version

### ISSUE THREAD

**Issue by constant-wip** [Paradoxis/facebook-csharp-ads-sdk#2]
Hi Luke,
    The current version (v 2.9) is already deprecated. Any plans on updating this package and also its documentation?
Thanks!

**Comment by Paradoxis** [comment]
I've updated it locally in the repository in commit 5288457<br>
Sadly I won't have time to update it on NuGet until this weekend.

**Comment by constant-wip** [comment]
Does it mean you are only updating the version number or you will be updating the whole package including the converter?

**Comment by Paradoxis** [comment]
I try to regenerate the entire package but I ran into an issue that caused none of the methods to be generated, I sadly can’t work on this during work hours so any patches are appreciated, I should have time tomorrow

**Comment by dnatabar** [comment]
Any news on the updated classes? =)

**Comment by ghostiq** [comment]
You are calling a deprecated version of the Ads API. Please update to the latest version: v2.11

**Comment by Paradoxis** [comment]
Sorry all for the late update, haven't had access to my nuget account. Just updated to the latest version. https://www.nuget.org/packages/Facebook-Ads-SDK/
