### ISSUE TITLE
Get all campaigns without knowing the id

### ISSUE THREAD

**Issue by Ethilyk** [Paradoxis/facebook-csharp-ads-sdk#3]
Is there are way to get a list of all the campaigns without knowing the ID of each campaign?

**Comment by Paradoxis** [comment]
Sorry, as of right now I wouldn’t exactly know how to do this as I haven’t used the API itself in a long time. I simply maintain the wrapper around it for C#. 

You might want to ask a question on stackoverflow on how to do it with the PHP sdk and if you have an example in that language I might be able to help you translate it to the C# variant :)

Hope it helps
