### ISSUE TITLE
Create new pixel or ad account using sdk

### ISSUE THREAD

**Issue by gauravamatya** [Paradoxis/facebook-csharp-ads-sdk#7]
Hi there,
I am trying to create a pixel with this sdk, as per facebook marketing api, it should be in `AdAccount("Ad Id").CreatePixel`, but on the sdk all I can see is Get Methods inside AdAccount. Please help me figure this out, how do I create pixel or Ad Account using this sdk. Your help will be much appreciated.

Thanks,
Gaurav

**Comment by Paradoxis** [comment]
The sdk was made in a time when there was no API playground for the business API, hence making a single call would cost money which I didn't really have at the time (as I was a student) so there was no way to test it, see [this](https://github.com/Paradoxis/Facebook-CSharp-Ads-SDK/issues/6) question for more info
